[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "omnia_timeseries"
version = "1.3.12"
authors = ["Equinor Omnia Industrial IoT Team <omniaindiot@equinor.com>"]
homepage = "https://github.com/equinor/omnia-timeseries-python"
repository = "https://github.com/equinor/omnia-timeseries-python"
description = "Official Python SDK for the Omnia Timeseries API"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
requests = "*"
azure-identity = ">=1.19.0"
requests-mock = "*"
pytest = "*"
azure-core = "*"
poetry = "^1.8.4"
build = "*"
opentelemetry-instrumentation-requests = "^0.54b1"
opentelemetry-api = "^1.27.0"
cryptography = ">=43.0.1"
pyjwt = ">=2.9.0"